version: '3.8'

services:
  frontend:
    build:
      context: ../Front-End
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ../Front-End:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
    networks:
      - pathsys-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - config.atlas.env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    networks:
      - pathsys-network
    restart: unless-stopped

networks:
  pathsys-network:
    driver: bridge
