version: '3.8'

services:
  # Aplicación FastAPI
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=lime_pathsys
      - ENVIRONMENT=development
      - DEBUG=True
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - pathsys-dev
    restart: unless-stopped

  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=lime_pathsys
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pathsys-dev
    restart: unless-stopped

  # MongoDB Express (interfaz web para MongoDB)
  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - pathsys-dev
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  pathsys-dev:
    driver: bridge